version: "3"
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
      
  ts-dev:
    image: node:23-alpine 
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev:all
    tty: true  # Keep the terminal open for interactive commands