version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
    - 8080:8080

  tailwind:
    image: node:23-alpine 
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npx tailwindcss -i ./src/css/style.css -o ./src/css/tailwind.css --watch
    tty: true  # Keep the terminal open for interactive commands