version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
    - 8080:8080

  tailwind:
    image: node:23-alpine  # You can use any Node.js version here
    working_dir: /app
    volumes:
      - ./frontend:/app  # Mount the current directory to the container
    command: npx tailwindcss -i ./css/style.css -o ./css/tailwind.css --watch
    tty: true  # Keep the terminal open for interactive commands